name: Check Domains

on:
  schedule:
    - cron: "*/1 * * * *" # Her 1 dakikada bir
  workflow_dispatch:

jobs:
  check_domains:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Node Kurulumu
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Bağımlılıkları Kur
        run: npm ci

      - name: Cypress Testlerini Çalıştır
        run: npx cypress run || true

      - name: Hataları Google Chat'e Gönder
        env:
          IMGUR_CLIENT_ID: ${{ secrets.IMGUR_CLIENT_ID }}
          GOOGLE_CHAT_WEBHOOK_URL: ${{ secrets.GOOGLE_CHAT_WEBHOOK_URL }}
        run: |
          if [ ! -f failures.json ]; then
            echo "Hata dosyası yok, çıkılıyor."
            exit 0
          fi

          FAILURES=$(cat failures.json)
          COUNT=$(echo "$FAILURES" | jq 'length')
          if [ "$COUNT" -eq 0 ]; then
            echo "Hata bulunamadı, çıkılıyor."
            exit 0
          fi

          MESSAGE="⚠️ PB Sağlık Kontrolü\nHatalı Hesaplar:\n"
          for row in $(echo "${FAILURES}" | jq -r '.[] | @base64'); do
            _jq() {
              echo ${row} | base64 --decode | jq -r ${1}
            }
            LINK="$(_jq '.url')"
            ERROR="$(_jq '.errorMessage')"
            SSFILE="$(_jq '.screenshot')"

            # Imgur'a yükle
            IMG_URL=""
            if [ -f "cypress/screenshots/cypress/e2e/$SSFILE" ]; then
              IMG_URL=$(curl -s -H "Authorization: Client-ID $IMGUR_CLIENT_ID" \
                -F "image=@cypress/screenshots/cypress/e2e/$SSFILE" https://api.imgur.com/3/image | jq -r '.data.link')
            fi

            MESSAGE+="❌ $ERROR\n🔗 $LINK\n"
            if [ "$IMG_URL" != "" ] && [ "$IMG_URL" != "null" ]; then
              MESSAGE+="🖼️ Ekran Görüntüsü: $IMG_URL\n"
            fi
            MESSAGE+="\n"
          done

          # Google Chat'e gönder
          JSON="{\"text\": \"$MESSAGE\"}"
          curl -X POST -H "Content-Type: application/json" \
            -d "$JSON" "$GOOGLE_CHAT_WEBHOOK_URL"

      - name: Hata dosyasını temizle
        if: always()
        run: rm -f failures.json