name: Check Domains

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  check_domains:
    runs-on: windows-latest

    steps:
      - name: Depoyu Kopyala
        uses: actions/checkout@v3

      - name: Node.js Kur
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: Cypress Binary Cache Kullan
        uses: actions/cache@v3
        with:
          path: ~/.cache/Cypress
          key: cypress-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            cypress-${{ runner.os }}-

      - name: Bağımlılıkları Yükle
        run: npm ci

      - name: Cypress Cache Kontrol ve Yükleme
        run: npx cypress install || echo "Cypress zaten yüklü"

      - name: Testleri Çalıştır ve Logları Kaydet
        run: npx cypress run --reporter=spec | tee cypress-output.log
      
      - name: Hatalı Domainleri Google Chat'e Gönder
        if: failure()
        run: |
          # LOG dosyasını oku
          $logPath = "cypress-output.log"
          if (Test-Path $logPath) {
              $failedTests = Get-Content $logPath | Select-String "🚨 HATA" -AllMatches
          } else {
              $failedTests = @()
          }
      
          if ($failedTests.Count -gt 0) {
              $message = "🚨 Domainlerde sorun tespit edildi!\n\n" + ($failedTests -join "`n")
          } else {
              $message = "🚨 Domainlerde sorun tespit edildi! (Ancak hata detayları loglarda bulunamadı.)"
          }
      
          # Mesajı Google Chat'e gönder
          $uri = "${{ secrets.GOOGLE_CHAT_WEBHOOK_URL }}"
          $body = @{ text = $message } | ConvertTo-Json -Depth 10
      
          Invoke-RestMethod -Uri $uri -Method Post -Body $body -ContentType "application/json"
        shell: pwsh
      