name: Check Domains

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  check_domains:
    runs-on: windows-latest

    steps:
      - name: Depoyu Kopyala
        uses: actions/checkout@v3

      - name: Node.js Kur
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: Bağımlılıkları Yükle
        run: npm ci

      - name: Cypress Binary Cache Kullan
        uses: actions/cache@v3
        with:
          path: ~/.cache/Cypress
          key: cypress-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            cypress-${{ runner.os }}-

      - name: Cypress Yükle
        run: npx cypress install || echo "Cypress zaten yüklü"

      - name: Testleri Çalıştır ve Logları Kaydet
        run: |
          npx cypress run --spec "cypress/e2e/request.cy.js" --reporter=dot 2>&1 | Tee-Object -FilePath cypress-output.log
          if ($LASTEXITCODE -ne 0) { exit 1 }

      - name: Cypress Loglarını Göster
        run: cat cypress-output.log

      - name: Hatalı Domainleri Google Chat'e Gönder
        if: failure()
        run: |
          $logPath = "cypress-output.log"
      
          if (!(Test-Path $logPath)) {
              Write-Output "Log dosyası bulunamadı!"
              exit 0
          }
      
          $logContent = Get-Content $logPath -Raw
          $messages = @()
      
          $patterns = @(
              "DO SUNUCUSUNU KONTROL EDİN",
              "SH2 SUNUCUSUNU KONTROL EDİN",
              "KNET SUNUCUSUNU KONTROL EDİN"
          )
      
          foreach ($pattern in $patterns) {
              if ($logContent -match $pattern) {
                  $messages += "🚨 $pattern"
              }
          }
      
          if ($messages.Count -eq 0) {
              Write-Output "Hatalı domain bulunamadı."
              exit 0
          }
      
          $message = "⚠️ *Domain Hataları Tespit Edildi!*`n" + ($messages -join "`n")
      
          Write-Output "📢 Google Chat'e gönderilecek mesaj:"
          Write-Output $message
      
          $uri = "${{ secrets.GOOGLE_CHAT_WEBHOOK_URL }}"
          $body = @{ text = $message } | ConvertTo-Json -Depth 10
      
          try {
              Invoke-RestMethod -Uri $uri -Method Post -Body $body -ContentType "application/json"
              Write-Output "✅ Google Chat mesajı gönderildi!"
          } catch {
              Write-Output "❌ Google Chat mesajı gönderilemedi: $_"
              exit 1
          }
        shell: pwsh
