name: Check Domains

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  check_domains:
    runs-on: ubuntu-latest

    steps:
      - name: Depoyu Kopyala
        uses: actions/checkout@v3

      - name: Node.js Kur ve Paketleri Yükle
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: Bağımlılıkları Yükle
        run: npm ci

      - name: Cypress Testlerini Çalıştır
        run: npx cypress run || true

      - name: Hatalı Domainler İçin Ekran Görüntülerini Yükle ve Google Chat'e Bildir
        env:
          IMGUR_CLIENT_ID: ${{ secrets.IMGUR_CLIENT_ID }}
          GOOGLE_CHAT_WEBHOOK_URL: ${{ secrets.GOOGLE_CHAT_WEBHOOK_URL }}
        run: |
          mkdir -p screenshots_flat

          if [ -d "cypress/screenshots" ]; then
            find cypress/screenshots -type f -name "*.png" -exec cp {} screenshots_flat/ \;
          else
            echo "📂 'cypress/screenshots' klasörü yok, screenshot bulunamadı."
          fi

          msg=$'⚠️ PB Health Check\n\n🟥 Hatalı Hesaplar:\n'

          uploaded_links=()
          for img in screenshots_flat/*.png; do
            response=$(curl -s --request POST "https://api.imgur.com/3/image" \
              --header "Authorization: Client-ID $IMGUR_CLIENT_ID" \
              --form "image=@$img")

            link=$(echo "$response" | jq -r '.data.link')

            filename=$(basename "$img")
            page_url=$(echo "$filename" | sed 's/_/\//g' | sed 's/\.png//g' | sed 's/^/https:\/\//')

            msg+=$'❌ Link: '"$page_url"$'\n → HATA GÖRÜLDÜ\n🔗 Ekran Görüntüsü: '"$link"$'\n\n'
          done

          if [ ${#uploaded_links[@]} -eq 0 ]; then
            msg+=$'✅ Hata veya ekran görüntüsü bulunamadı.'
          fi

          jq -n --arg text "$msg" '{ text: $text }' > message.json

          curl -X POST "$GOOGLE_CHAT_WEBHOOK_URL" \
            -H "Content-Type: application/json" \
