name: Check Domains

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  check_domains:
    runs-on: ubuntu-latest

    steps:
      - name: Kodu Klonla
        uses: actions/checkout@v3

      - name: Node Kurulumu
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Bağımlılıkları Kur
        run: npm ci

      - name: Önceki Logları Temizle
        run: rm -f cypress-output.log || true

      - name: Cypress Testlerini Çalıştır
        run: npx cypress run || true

      - name: Google Chat'e Hataları Gönder
        shell: pwsh
        run: |
          $logPath = "cypress-output.log"
          if (!(Test-Path $logPath)) {
            Write-Host "Hata log dosyası yok, çıkılıyor."
            exit 0
          }

          $hatalar = Get-Content $logPath | Where-Object { $_ -like "HATA:*" }

          if ($hatalar.Count -eq 0) {
            Write-Host "Hata bulunamadı, çıkılıyor."
            exit 0
          }

          $message = "⚠️ **PB Sağlık Kontrolü**`n`n**Hatalar:**`n"
          foreach ($hata in $hatalar) {
            $message += "❌ $hata`n"
          }

          $body = @{ text = $message } | ConvertTo-Json -Depth 10

          Invoke-RestMethod -Uri "${{ secrets.GOOGLE_CHAT_WEBHOOK_URL }}" `
            -Method POST `
            -Body $body `
            -ContentType "application/json"
