name: Check Domains

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  check_domains:
    runs-on: ubuntu-latest

    steps:
      - name: Depoyu Kopyala
        uses: actions/checkout@v3

      - name: Node.js Kur
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: Cypress Binary Cache Kullan
        uses: actions/cache@v3
        with:
          path: ~/.cache/Cypress
          key: cypress-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            cypress-${{ runner.os }}-

      - name: Bağımlılıkları Yükle
        run: npm ci

      - name: Cypress Cache Kontrol ve Yükleme
        run: npx cypress install || echo "Cypress zaten yüklü"

      - name: Testleri Çalıştır
        run: npx cypress run

      - name: Hata Durumunda Google Chat Mesajı Gönder
        if: failure()
        run: |
          curl -X POST -H 'Content-Type: application/json' \
          -d '{"text": "⚠️ Domain kontrol testleri başarısız oldu!"}' \
          ${{ secrets.GOOGLE_CHAT_WEBHOOK_URL }}