name: Check Domains

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  check_domains:
    runs-on: ubuntu-latest

    steps:
      - name: Kodu Klonla
        uses: actions/checkout@v3

      - name: Node Kurulumu
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Bağımlılıkları Kur
        run: npm ci

      - name: Cypress Testlerini Çalıştır
        run: npx cypress run || true

      - name: Hatalı Domainleri Google Chat'e Bildir
        run: |
          if [ -f "failures.json" ]; then
            errors=""
            while IFS= read -r line; do
              url=$(echo "$line" | jq -r '.url')
              message="❌ Link: $url →\n"

              # Screenshot dosya adını oluştur
              img_name=$(echo "$url" | sed 's|https://||;s|/|_|g')
              img_path="cypress/screenshots/${img_name}.png"

              # Ekran görüntüsünü Imgur'a yükle
              if [ -f "$img_path" ]; then
                base64_image=$(base64 "$img_path" | tr -d '\n')
                response=$(curl -s --request POST "https://api.imgur.com/3/image" \
                  --header "Authorization: Client-ID ${{ secrets.IMGUR_CLIENT_ID }}" \
                  --form "image=$base64_image")
                imgur_url=$(echo "$response" | jq -r '.data.link')
              else
                imgur_url="Ekran görüntüsü bulunamadı"
              fi

              message+="🖼️ Ekran Görüntüsü: $imgur_url\n\n"
              errors+="$message"
            done < <(jq -c '.[]' failures.json)

            if [ -n "$errors" ]; then
              full_message="⚠️ **PB Sağlık Kontrolü**\n\n**Hatalı Hesaplar:**\n\n$errors"
              curl -X POST "${{ secrets.GOOGLE_CHAT_WEBHOOK_URL }}" \
                -H "Content-Type: application/json" \
                -d "$(jq -n --arg text "$full_message" '{ text: $text }')"
            fi
          fi
