name: Check Domains

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  check_domains:
    runs-on: ubuntu-latest

    steps:
      - name: Depoyu Kopyala
        uses: actions/checkout@v3

      - name: Node.js Kur
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Bağımlılıkları Yükle
        run: npm install

      - name: Testleri Çalıştır
        run: npx cypress run

      - name: Hata Durumunda E-posta Gönder
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USER }}
          password: ${{ secrets.EMAIL_PASS }}
          subject: "Domain Kontrol Uyarısı!"
          body: "⚠️ Domainlerde sorun tespit edildi!"
          to: "ilker@lityum.com"
          from: "Bot <bot@example.com>"
