name: Check Domains

on:
  workflow_dispatch:
  schedule:
    - cron: "*/1 * * * *"

jobs:
  check_domains:
    runs-on: ubuntu-latest

    steps:
      - name: Depoyu Klonla
        uses: actions/checkout@v3

      - name: Node Kurulumu
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Paketleri Yükle
        run: npm ci

      - name: Cypress Testini Çalıştır
        run: |
          rm -f failures.json
          npx cypress run || true

      - name: Google Chat'e Bildir
        if: always()
        run: |
          mkdir -p screenshots_flat
          find cypress/screenshots -type f -name "*.png" -exec cp {} screenshots_flat/ \;

          if [ -f "failures.json" ]; then
            errors=""
            while IFS= read -r line; do
              url=$(echo "$line" | jq -r '.url')
              img_name=$(echo "$url" | sed 's|https://||;s|/|_|g')
              img_file="screenshots_flat/${img_name}.png"

              if [ -f "$img_file" ]; then
                base64_image=$(base64 "$img_file" | tr -d '\n')
                response=$(curl -s --request POST "https://api.imgur.com/3/image" \
                  --header "Authorization: Client-ID ${{ secrets.IMGUR_CLIENT_ID }}" \
                  --form "image=$base64_image")
                imgur_url=$(echo "$response" | jq -r '.data.link')
              else
                imgur_url="(Görsel bulunamadı)"
              fi

              errors+="❌ Link: $url → \n🖼️ Ekran Görüntüsü: $imgur_url\n\n"
            done < <(jq -c '.[]' failures.json)

            if [ -n "$errors" ]; then
              message="⚠️ **PB Sağlık Kontrolü**\n\n**Hatalı Hesaplar:**\n\n$errors"
              curl -X POST "${{ secrets.GOOGLE_CHAT_WEBHOOK_URL }}" \
                -H "Content-Type: application/json" \
                -d "$(jq -n --arg text "$message" '{ text: $text }')"
            fi
          fi
