name: Check Domains

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  check_domains:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Node Kurulumu
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Bağımlılıkları Kur
        run: npm ci

      - name: Cypress Testlerini Çalıştır
        run: npx cypress run || true

      - name: Google Chat'e Hataları Gönder
        shell: pwsh
        run: |
          $jsonPath = "failures.json"
          if (!(Test-Path $jsonPath)) {
            Write-Host "Hata dosyası yok, çıkılıyor."
            exit 0
          }

          $failures = Get-Content $jsonPath | ConvertFrom-Json

          if (!$failures -or $failures.Count -eq 0) {
            Write-Host "Hata bulunamadı, çıkılıyor."
            exit 0
          }

          $message = "⚠️ **PB Sağlık Kontrolü**`n`n**Hatalar:**`n"
          foreach ($failure in $failures) {
            $message += "❌ $($failure.errorMessage)`n🔗 $($failure.url)`n🖼️ Ekran görüntüsü: $($failure.screenshot)`n`n"
          }

          $body = @{ text = $message } | ConvertTo-Json -Depth 10

          try {
            Invoke-RestMethod -Uri "${{ secrets.GOOGLE_CHAT_WEBHOOK_URL }}" `
              -Method POST `
              -Body $body `
              -ContentType "application/json"
            Write-Host "Google Chat'e mesaj gönderildi."
          } catch {
            Write-Error "Google Chat mesaj gönderimi başarısız: $_"
            exit 1
          }
