name: Check Domains

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  check_domains:
    runs-on: windows-latest

    steps:
      - name: Depoyu Kopyala
        uses: actions/checkout@v3

      - name: Node.js Kur ve Paketleri Yükle
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: Bağımlılıkları Yükle
        run: npm ci

      - name: Testleri Çalıştır ve Logları Kaydet
        run: npx cypress run | tee cypress-output.log
        shell: bash

      - name: Hatalı veya Yavaş Domainleri Google Chat'e Gönder
        if: failure()
        run: |
          $logPath = "cypress-output.log"
          if (!(Test-Path $logPath)) {
              exit 0
          }

          # Log'u oku
          $logContent = Get-Content $logPath -Raw

          # ANSI escape kodlarını temizle
          $logContent = $logContent -replace "`e\[[\d;]*m", ""

          $errorMessages = @()
          $slowMessages = @()

          # Hataları ve uyarıları ayır
          foreach ($line in $logContent -split "`n") {
              if ($line -match "HATA:") {
                  $errorMessages += "🟥 $line"
              } elseif ($line -match "UYARI:") {
                  $slowMessages += "🟨 $line"
              }
          }

          if ($errorMessages.Count -eq 0 -and $slowMessages.Count -eq 0) {
              exit 0
          }

          # Mesajı oluştur
          $message = "⚠️ **Sunucu Sağlık Kontrolü Sonucu**`n"

          if ($errorMessages.Count -gt 0) {
              $message += "`n🟥 **Hatalı Sunucular:**`n" + ($errorMessages -join "`n")
          }

          if ($slowMessages.Count -gt 0) {
              $message += "`n`n🟨 **Yavaş Sunucular:**`n" + ($slowMessages -join "`n")
          }

          $uri = "${{ secrets.GOOGLE_CHAT_WEBHOOK_URL }}"
          $body = @{ text = $message } | ConvertTo-Json -Depth 10

          try {
              Invoke-RestMethod -Uri $uri -Method Post -Body $body -ContentType "application/json"
          } catch {
              exit 1
          }
        shell: pwsh
