name: Check Domains

on:
  schedule:
    - cron: "*/30 * * * *" # 30 dakikada bir kontrol
  workflow_dispatch:

jobs:
  check_domains:
    runs-on: ubuntu-latest

    steps:
      - name: Depoyu Kopyala
        uses: actions/checkout@v3

      - name: Node.js Kur ve Paketleri Yükle
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: Bağımlılıkları Yükle
        run: npm ci

      - name: Cypress Testlerini Çalıştır
        run: npx cypress run

      - name: Ekran Görüntülerini Yükle ve Google Chat'e Bildir
        if: always()
        run: |
          mkdir -p screenshots_flat

          if [ -d "cypress/screenshots" ]; then
            find cypress/screenshots -type f -name "*.png" -exec cp {} screenshots_flat/ \;
          fi

          msg="⚠️ **Sunucu Sağlık Kontrolü Sonucu**\n\n"
          error_block=""

          for img in screenshots_flat/*.png; do
            base64_image=$(base64 "$img" | tr -d '\n')
            response=$(curl -s --request POST "https://api.imgur.com/3/image" \
              --header "Authorization: Client-ID ${{ secrets.IMGUR_CLIENT_ID }}" \
              --form "image=$base64_image")

            link=$(echo "$response" | jq -r '.data.link')
            domain_name=$(basename "$img" | cut -d' ' -f1)
            readable_name=$(echo "$domain_name" | sed 's/\./\\./g')

            error_msg=$(grep "$readable_name" cypress/e2e/request.cy.js | cut -d'"' -f8)

            error_block+="❌ HATA: https://${domain_name}/user/login → ${error_msg}\n"
            error_block+="🖼️ Screenshot: $link\n\n"
          done

          if [ -z "$error_block" ]; then
            msg+="✅ Hata veya ekran görüntüsü bulunamadı."
          else
            msg+="**Hatalı Sunucular:**\n\n${error_block}"
          fi

          curl -X POST "${{ secrets.GOOGLE_CHAT_WEBHOOK_URL }}" \
            -H "Content-Type: application/json" \
            -d "$(jq -n --arg text "$msg" '{ text: $text }')"
