name: Check Domains

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  check_domains:
    runs-on: ubuntu-latest

    steps:
      - name: Kodu Klonla
        uses: actions/checkout@v3

      - name: Node Kurulumu
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Bağımlılıkları Kur
        run: npm ci

      - name: Cypress Testlerini Çalıştır
        run: npx cypress run || true

      - name: Google Chat'e Hataları Gönder (Ekran Görüntülü)
  shell: pwsh
  run: |
    $logPath = "cypress-output.log"
    if (!(Test-Path $logPath)) { exit 0 }

    $hatalar = @()

    foreach ($line in Get-Content $logPath) {
      if ($line -match "HATA:") {
        $url = $line -replace ".*HATA: ", ""

        $imgName = $url -replace "https://", "" -replace "/", "_"
        $imgPath = "cypress/screenshots/${imgName}.png"

        if (Test-Path $imgPath) {
          $imgData = [Convert]::ToBase64String([IO.File]::ReadAllBytes($imgPath))
          $res = Invoke-RestMethod -Uri "https://api.imgur.com/3/image" `
            -Headers @{ Authorization = "Client-ID ${{ secrets.IMGUR_CLIENT_ID }}" } `
            -Method POST -Body @{ image = $imgData } -ContentType "application/x-www-form-urlencoded"
          $imgUrl = $res.data.link
        } else {
          $imgUrl = "Ekran görüntüsü bulunamadı"
        }

        $hatalar += "❌ Link: $url`n🖼️ Ekran Görüntüsü: $imgUrl`n"
      }
    }

    if ($hatalar.Count -eq 0) { exit 0 }

    $message = "⚠️ **PB Sağlık Kontrolü**`n`n**Hatalı Hesaplar:**`n`n" + ($hatalar -join "`n")
    $body = @{ text = $message } | ConvertTo-Json -Depth 10

    Invoke-RestMethod -Uri "${{ secrets.GOOGLE_CHAT_WEBHOOK_URL }}" `
      -Method POST `
      -Body $body `
      -ContentType "application/json"
