name: Check Domains

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  check_domains:
    runs-on: windows-latest

    steps:
      - name: Depoyu Kopyala
        uses: actions/checkout@v3

      - name: Node.js Kur
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: Bağımlılıkları Önbelleğe Al
        uses: actions/cache@v3
        with:
          path: node_modules
          key: npm-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            npm-${{ runner.os }}-

      - name: Bağımlılıkları Yükle (Eğer Önbellek Yoksa)
        run: npm ci
        if: steps.cache.outputs.cache-hit != 'true'

      - name: Cypress Binary Cache Kullan
        uses: actions/cache@v3
        with:
          path: ~/.cache/Cypress
          key: cypress-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            cypress-${{ runner.os }}-

      - name: Cypress Cache Kontrol ve Yükleme
        run: npx cypress install || echo "Cypress zaten yüklü"

      - name: Testleri Çalıştır ve Logları Kaydet
        run: |
          npx cypress run --reporter=dot 2>&1 | Tee-Object -FilePath cypress-output.log
          if ($LASTEXITCODE -ne 0) { exit 1 } # Cypress hata verirse job başarısız say

      - name: Cypress Loglarını Göster
        run: cat cypress-output.log

      - name: Hatalı Domainleri Google Chat'e Gönder
        if: failure()
        run: |
          $logPath = "cypress-output.log"
          if (Test-Path $logPath) {
              $failedTests = Get-Content $logPath | Select-String "🔥 LOG HATASI" -AllMatches
          } else {
              $failedTests = @()
          }

          # Hatalı domainleri belirle
          $messages = @()
          if ($failedTests | Select-String "demo.peoplebox.biz") { $messages += "🚨 DO SUNUCUSUNU KONTROL EDİN!" }
          if ($failedTests | Select-String "demo212321.peoplebox.biz") { $messages += "🚨 SH2 SUNUCUSUNU KONTROL EDİN!" }
          if ($failedTests | Select-String "demo912312.peoplebox.biz") { $messages += "🚨 KNET SUNUCUSUNU KONTROL EDİN!" }

          # Mesaj oluştur
          if ($messages.Count -gt 0) {
              $message = "⚠️ *Domain Hataları Tespit Edildi!*`n" + ($messages -join "`n")
          } else {
              exit 0 # Eğer hata yoksa mesaj göndermeyelim
          }

          # DEBUG: Mesajı göster
          Write-Output "📢 Google Chat'e gönderilecek mesaj:"
          Write-Output $message

          # Google Chat'e mesaj gönder
          $uri = "${{ secrets.GOOGLE_CHAT_WEBHOOK_URL }}"
          $body = @{ text = $message } | ConvertTo-Json -Depth 10

          try {
              Invoke-RestMethod -Uri $uri -Method Post -Body $body -ContentType "application/json"
              Write-Output "✅ Google Chat mesajı gönderildi!"
          } catch {
              Write-Output "❌ Google Chat mesajı gönderilemedi: $_"
              exit 1
          }
        shell: pwsh
