name: Check Domains

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  check_domains:
    runs-on: windows-latest

    steps:
      - name: Depoyu Kopyala
        uses: actions/checkout@v3

      - name: Node.js Kur ve Paketleri Yükle
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: Bağımlılıkları Yükle
        run: npm ci

      - name: Testleri Çalıştır ve Logları Kaydet
        run: npx cypress run | tee cypress-output.log
        shell: bash

      - name: Cypress Screenshotları Artifact olarak Yükle
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: cypress-screenshots
          path: cypress/screenshots

      - name: Hatalı Domainleri Google Chat'e Gönder
        if: failure()
        run: |
          $logPath = "cypress-output.log"
          if (!(Test-Path $logPath)) {
              exit 0
          }

          $logContent = Get-Content $logPath -Raw
          $messages = @()

          $patterns = @(
              "DO SUNUCUSUNU KONTROL EDİN",
              "SH2 SUNUCUSUNU KONTROL EDİN",
              "KNET SUNUCUSUNU KONTROL EDİN"
          )

          foreach ($pattern in $patterns) {
              if ($logContent -match $pattern) {
                  $messages += "🚨 $pattern"
              }
          }

          if ($messages.Count -eq 0) {
              exit 0
          }

          $message = "⚠️ **`n" + ($messages -join "`n")

          $uri = "${{ secrets.GOOGLE_CHAT_WEBHOOK_URL }}"
          $body = @{ text = $message } | ConvertTo-Json -Depth 10

          try {
              Invoke-RestMethod -Uri $uri -Method Post -Body $body -ContentType "application/json"
          } catch {
              exit 1
          }
        shell: pwsh
